
theme: minima
title: Jacob Erlikhman
defaults:
  - scope:
      path: "assets/137b/worksheets"
    values:
      137b: true
header_pages:
  - index.html
  - organization.md
  - teaching.md
  - writings.md
plugins:
  - jekyll-feed
  - jekyll-seo-tag
