
theme: minima
title: Jacob Erlikhman
defaults:
  - scope:
      path: "assets/137b/worksheets"
    values:
      137b: true
kramdown:
  math_engine: katex
plugins:
  - jekyll-feed
  - jekyll-seo-tag
